server:
  port: 8888

spring:
  application:
    name: taste-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zpl25809
    url: jdbc:mysql://localhost:3306/taste?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
  security:
    user:
      name: moonerHigh
      password: moonerHigh
      roles: ADMIN

mybatis-plus:
  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted #默认逻辑删除字段
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto

